// <auto-generated/>
using System;
using System.IO;
using MasterMemory;
using MessagePack;
using MessagePack.Resolvers;

namespace GameData
{
    internal static class ItemBuilder
    {
        /// <summary>
        /// Item 配列から MasterMemory バイナリを生成し保存します。
        /// </summary>
        /// <param name="masters">Item 配列</param>
        /// <param name="outputPath">出力パス。未指定時 'Assets/Example/Binary/Item.bytes'。</param>
        /// <returns>生成されたバイナリ</returns>
        public static byte[] Build(Item[] masters, string outputPath = null)
        {
            if (masters == null) throw new ArgumentNullException(nameof(masters));
            outputPath = string.IsNullOrWhiteSpace(outputPath) ? "Assets/Example/Binary/Item.bytes" : outputPath;

            var messagePackResolvers = CompositeResolver.Create(
                MasterMemoryResolver.Instance,
                StandardResolver.Instance
            );
            var options = MessagePackSerializerOptions.Standard.WithResolver(messagePackResolvers);
            MessagePackSerializer.DefaultOptions = options;

            var builder = new DatabaseBuilder();
            builder.Append(masters);
            var binary = builder.Build();

            var dir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllBytes(outputPath, binary);

            return binary;
        }
    }
}
