// <auto-generated />
using ExcelMaster;
using MasterMemory;
using MessagePack;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace GameData
{
    [MemoryTable("Item")]
    [MessagePackObject(true)]
    public class Item
    {
        [PrimaryKey]
        public int Id { get; set; }

        public string Name { get; set; }

        public float[] Parameters { get; set; }

        public string[] Addresses { get; set; }

        public int IntSample { get; set; }

        public float[] FloatArraySample { get; set; }

        public EnumSample EnumSample { get; set; }

        public HandType HandType { get; set; }

        public Category Category { get; set; }
    }

    public enum EnumSample
    {
        Member1,
        Member2,
        Member3
    }

    public enum HandType
    {
        Goo,
        Pa
    }

    public enum Category
    {
        Potion,
        Equipment,
        Weapon
    }
}
